version: '3.9'

services:
  api:
    build: .
    container_name: pokedex-api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/pokedex_db
      - POKEAPI_BASE_URL=https://pokeapi.co/api/v2
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - pokedex-network
    restart: unless-stopped

  mongo:
    image: mongo:7-jammy
    container_name: pokedex-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - pokedex-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  pokedex-network:
    driver: bridge

volumes:
  mongo_data: